name: Auto Pull Request

on:
  push:
    branches-ignore:
      - main
permissions:
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create pull request
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          REPO="${{ github.repository }}"
          OWNER="${{github.repository_owner}}"
          BRANCH="${{ github.ref_name }}"
          HEAD=$OWNER:$BRANCH
          curl -X POST \
            -H "Authorization: token $TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO/pulls" \
            -d "{
                  \"title\": \"Auto Merge Changes from $BRANCH to main\",
                  \"body\": \"This pull request was automatically created to merge changes into the main branch.\",
                  \"head\": \"$HEAD\",
                  \"base\": \"main\"
                }"
